const ActionName = {
  FETCH_FOOD: "FETCH_FOOD",
  FETCH_USER: "FETCH_USER",
  FETCH_ORDER: "FETCH_ORDER",
  ADD_FOOD: "ADD_FOOD",
  ADD_ORDER: "ADD_ORDER",
  ADD_USER: "ADD_USER",
  DELETE_USER: "DELETE_USER",
  DELETE_FOOD: "DELETE_FOOD",
  UPDATE_USER: "UPDATE_USER",
  UPDATE_FOOD: "UPDATE_FOOD",
};

export { ActionName };
